package e2e

import (
	"context"
	"encoding/json"
	"testing"

	"github.com/openbotstack/openbotstack-core/assistant"
	"github.com/openbotstack/openbotstack-core/planner"
	"github.com/stretchr/testify/require"
)

func TestE2E_PatientSummary(t *testing.T) {
	ar := setupRuntime(t)
	ctx := context.Background()

	pCtx := &planner.PlannerContext{
		AssistantID: "test-icu-assistant",
		UserRequest: "Please summarize patient P001",
		Soul:        assistant.DefaultSoul(),
		Skills: []planner.SkillDescriptor{
			{ID: "workflow.patient_summary", Name: "Patient Summary", Description: "Summarizes patient status based on their EHR"},
		},
	}

	plan, err := ar.Planner.Plan(ctx, pCtx)
	require.NoError(t, err, "Planner should succeed")
	require.NotEmpty(t, plan.Steps, "Plan should have steps")
	require.Equal(t, "workflow.patient_summary", plan.Steps[0].Name)

	results, err := executePlanLocally(ctx, ar.ToolRunner.(*LocalToolRunner), plan)
	require.NoError(t, err, "Tool execution should succeed")
	require.Len(t, results, 5, "Patient summary expands to 5 tool steps")

	resultsJSON, _ := json.MarshalIndent(results[len(results)-1].Output, "", "  ")
	finalPrompt := "User wanted a patient summary. The summary generated by the tool is:\n" + string(resultsJSON) + "\n\nPlease write the final response to the user."

	var finalResponse string
	stream, err := ar.ModelProvider.Stream(finalPrompt)
	require.NoError(t, err)

	for token := range stream {
		finalResponse += token
	}

	require.NotEmpty(t, finalResponse, "Final response should not be empty")
	t.Logf("Final Response for Patient Summary:\n%s", finalResponse)
}
